# Generated by Django 4.2 on 2026-04-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('headquarters', models.CharField(max_length=100)),
                ('collector_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=50, unique=True)),
                ('taluk', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('REVENUE', 'Revenue Land'), ('PORAMBOKE', 'Poramboke Land'), ('FOREST', 'Forest Land'), ('WATER', 'Water Body / Lake / River Buffer'), ('INSTITUTION', 'Public Institution Land'), ('ROAD', 'Road / Highway Reserve')], max_length=20)),
                ('area_sqm', models.FloatField()),
                ('legal_status', models.CharField(choices=[('CLEAR', 'Clear'), ('DISPUTED', 'Disputed'), ('LITIGATION', 'Under Litigation'), ('ENCROACHED', 'Encroached')], max_length=20)),
                ('geometry', models.TextField()),
                ('gazette_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('last_satellite_scan', models.DateTimeField(blank=True, null=True)),
                ('encroachment_risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='satellite/parcels/')),
                ('capture_date', models.DateField()),
                ('image_type', models.CharField(choices=[('BEFORE', 'Before Image'), ('AFTER', 'After Image'), ('CURRENT', 'Current State')], max_length=20)),
                ('source', models.CharField(default='Sentinel-2', max_length=100)),
                ('cloud_coverage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='lands.landparcel')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('DISTRICT_OFFICER', 'District Revenue Officer'), ('FIELD_OFFICER', 'Field Inspector')], max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='landparcel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.officer'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.district'),
        ),
        migrations.CreateModel(
            name='LandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PATTA', 'Patta'), ('CHITTA', 'Chitta'), ('FMB', 'FMB Sketch'), ('GAZETTE', 'Gazette Notification'), ('COURT', 'Court Order'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='documents/parcels/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lands.landparcel')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.officer')),
            ],
        ),
        migrations.CreateModel(
            name='EncroachmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CONSTRUCTION', 'Unauthorized Construction'), ('VEGETATION', 'Vegetation Clearing'), ('WATER', 'Water Body Encroachment'), ('BOUNDARY', 'Boundary Violation'), ('LAND_USE', 'Land Use Change'), ('OTHER', 'Other')], max_length=20)),
                ('detection_method', models.CharField(choices=[('ML_AUTO', 'ML Auto Detection'), ('SATELLITE', 'Satellite Manual Review'), ('FIELD', 'Field Officer Report'), ('PUBLIC', 'Public Complaint')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('ml_confidence_score', models.FloatField(blank=True, null=True)),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('escalated_to_collector', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('after_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_after', to='lands.satelliteimage')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to='lands.officer')),
                ('before_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_before', to='lands.satelliteimage')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='lands.landparcel')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_alerts', to='lands.officer')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='lands.officer')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('SCAN', 'Satellite Scan Run'), ('ALERT', 'Alert Raised'), ('ESCALATE', 'Alert Escalated'), ('RESOLVE', 'Alert Resolved'), ('EXPORT', 'Data Exported')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.encroachmentalert')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.officer')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.landparcel')),
            ],
        ),
    ]
