# Generated by Django 6.0.4 on 2026-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landparcel',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='landparcel',
            name='legal_status',
        ),
        migrations.AddField(
            model_name='landparcel',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='status',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('DISPUTED', 'Disputed'), ('ENCROACHED', 'Encroached')], default='SAFE', max_length=20),
        ),
    ]
